spring:
  profiles.active: local
  # 데이터 소스 설정
  datasource:
    ## mySQL url, id, pw 설정해주세요
    url: jdbc:mysql://tt.cpsdhebt0ibj.ap-northeast-2.rds.amazonaws.com:3306/tt?serverTimezone=Asia/Seoul
    username: root
    password: triptogether
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  # Security OAuth
  security:
    oauth2.client:
      registration:
        naver:
          clientId: saJa0_ImC58QMscsiBVd
          clientSecret: 5pnrJiISiA
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://localhost:8080/{action}/oauth2/code/{registrationId}"
          scope: name, email, nickname, gender, age, mobile
          clientName: Naver

        kakao:
          clientId: 0bc8538cd642b69ae1bdf191401ea146
          clientSecret: 75S7o8EryGIZGutXb82ncabRIhsoK4q2
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://localhost:8080/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - account_email
            - gender
            - age_range
          clientName: Kakao
      # Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id

  thymeleaf:
    enabled: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt.secret: 'leeeunji990616pjw040928kjk000909'